### ISSUE TITLE
[JOSS] Language of status and error messages

### ISSUE THREAD

**Issue by anitagraser** [ni1o1/transbigdata#11]
I've been going through `Example 1-Taxi GPS data processing.ipynb` and found that some messages are in Chinese:

![image](https://user-images.githubusercontent.com/590385/148656805-df118112-0504-42e3-966b-3ae000b193d4.png)

![image](https://user-images.githubusercontent.com/590385/148656816-850a03d0-62d5-4859-bd5c-632371fc478e.png)

Considering a potentially global user base, I think the messages should be in English.

xref: [openjournals/joss-reviews#4021](https://github.com/openjournals/joss-reviews/issues/4021)

**Comment by anitagraser** [comment]
On a similar note, it would be nice to have Englisch examples in the notebooks, e.g. `Example 2-Identifying arrival and departure information from Bus GPS data.ipynb`

![image](https://user-images.githubusercontent.com/590385/148657384-67c5b96b-cacf-4d0e-96e5-4df0bd192109.png)

**Comment by ni1o1** [comment]
This example includes busstop name in Chinese, we have translate it into English so that it can display normally. [Example 2-Identifying arrival and departure information from Bus GPS data.ipynb](https://github.com/ni1o1/transbigdata/blob/main/example/Example%202-Identifying%20arrival%20and%20departure%20information%20from%20Bus%20GPS%20data.ipynb)

We have translated all docstrings, error messages and comments into English, include the Ipynb notebook examples. [Example 5-community detection for bikesharing data.ipynb](https://github.com/ni1o1/transbigdata/blob/main/example/Example%205-community%20detection%20for%20bikesharing%20data.ipynb) is also in English now.

**Comment by anitagraser** [comment]
Great work.
